-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 18:58:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_juego
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_juego
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_juego` DEFAULT CHARACTER SET utf8 ;
USE `sistema_juego` ;

-- -----------------------------------------------------
-- Table `sistema_juego`.`TpoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_juego`.`TpoUsuario` (
  `id_tpo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tpo_usuario`),
  UNIQUE INDEX `id_tpo_usuario_UNIQUE` (`id_tpo_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_juego`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_juego`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_juego`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_juego`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `TpoUsuario_id_tpo_usuario` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  INDEX `fk_Usuario_TpoUsuario1_idx` (`TpoUsuario_id_tpo_usuario` ASC),
  INDEX `fk_Usuario_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_Usuario_TpoUsuario1`
    FOREIGN KEY (`TpoUsuario_id_tpo_usuario`)
    REFERENCES `sistema_juego`.`TpoUsuario` (`id_tpo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `sistema_juego`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_juego`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_juego`.`Juego` (
  `idJuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idJuego`),
  UNIQUE INDEX `idJuego_UNIQUE` (`idJuego` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_juego`.`Puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_juego`.`Puntuacion` (
  `idPuntuacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `Juego_idJuego` INT NOT NULL,
  PRIMARY KEY (`idPuntuacion`, `id_usuario`),
  UNIQUE INDEX `idPuntuacion_UNIQUE` (`idPuntuacion` ASC),
  INDEX `fk_Puntuacion_Usuario_idx` (`id_usuario` ASC),
  INDEX `fk_Puntuacion_Juego1_idx` (`Juego_idJuego` ASC),
  CONSTRAINT `fk_Puntuacion_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_juego`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntuacion_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `sistema_juego`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
